### ISSUE TITLE
Change Background images in cover photo

### ISSUE THREAD

**Issue by inesiwadare** [BlickLabs/alegpaez#39]
Leave the first one, but the other 4 change them to these:

![alisa-anton-140249](https://cloud.githubusercontent.com/assets/17226545/23229409/d05cba36-f905-11e6-9b63-84c4257a7cdb.jpg)

![baked-healthy-fitness-broccoli-pie-with-basil-picjumbo-com](https://cloud.githubusercontent.com/assets/17226545/23229428/dce97b18-f905-11e6-8577-b0d4b7e27420.jpg)

![chris-lawton-165884](https://cloud.githubusercontent.com/assets/17226545/23229433/e87b1342-f905-11e6-8be4-8d9615b6567b.jpg)

![healthy-morning-dessert-blueberries-sundae-picjumbo-com](https://cloud.githubusercontent.com/assets/17226545/23229441/eed45abe-f905-11e6-8d41-02d7f6c10608.jpg)

**Comment by Enrique199413** [comment]
@inesiwadare remember I need one more image ;)
